export const ACTIONS = 'ACTIONS';
export const SET_WELLS = 'SET_WELLS';
export const SET_LOGS = 'SET_LOGS';
export const SET_FORMATIONS = 'SET_FORMATIONS';
export const SET_PLOTS = 'SET_PLOTS';
export const SET_SELECTED_WELLS = 'SET_SELECTED_WELLS';
export const SET_SELECTED_LOGS = 'SET_SELECTED_LOGS';
export const SET_SELECTED_FORMATIONS = 'SET_SELECTED_FORMATIONS';
